[workspace]
members = ["jupiter-swap-api-client"]

[workspace.package]
edition = "2021"

[workspace.dependencies]
solana-sdk = "~2.0"
solana-client = "~2.0"
solana-account-decoder = "~2.0"
spl-token = "=4.0.1"
